# Generated by Django 4.1.4 on 2022-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0002_timemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='address',
            field=models.CharField(default='تهران-برج میلاد', max_length=500),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[('Start', 'فروش بلیط شروع شده است'), ('End', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل شده است'), ('Sales', 'در حال فروش بلیط')]),
        ),
    ]
