# Generated by Django 4.1.4 on 2022-12-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0003_alter_locationmodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='فامیل')),
                ('status', models.IntegerField(choices=[('man', 'مرد'), ('woman', 'زن')], verbose_name='جنسیت')),
                ('profileimage', models.ImageField(upload_to='profileimage/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
            },
        ),
        migrations.AlterModelOptions(
            name='consertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'مکان کنسرت', 'verbose_name_plural': 'مکان کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'زمان ', 'verbose_name_plural': 'زمان '},
        ),
        migrations.AddField(
            model_name='consertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='consertimage/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='consertmodel',
            name='length',
            field=models.IntegerField(verbose_name='زمان کنسرت'),
        ),
        migrations.AlterField(
            model_name='consertmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name=' نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='consertmodel',
            name='singername',
            field=models.CharField(max_length=100, verbose_name='خواننده'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='address',
            field=models.CharField(default='تهران-برج میلاد', max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='capacity',
            field=models.IntegerField(verbose_name='گنجایش'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مکان'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='consert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.consertmodel', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.locationmodel', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='seats',
            field=models.IntegerField(verbose_name='صندلی'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='startdatetime',
            field=models.DateTimeField(verbose_name='ساعت و تاریخ'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[('Start', 'فروش بلیط شروع شده است'), ('End', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل شده است'), ('Sales', 'در حال فروش بلیط')], verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('ticketimage', models.ImageField(upload_to='ticketimage/', verbose_name='عکس')),
                ('profilemodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.profilemodel', verbose_name='پروفایل')),
                ('timemodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel', verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
