# Generated by Django 4.1.4 on 2022-12-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ticketsales', '0005_alter_profilemodel_status_alter_timemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='profilemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel', verbose_name='پروفایل'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
