# Generated by Django 4.1.4 on 2022-12-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0006_alter_ticketmodel_profilemodel_delete_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'این سانس کنسل شده است'), (4, ' در حال حاضر فروش بلیط شروع شده است')], verbose_name='وضعیت'),
        ),
    ]
